# Generated by Django 5.2 on 2025-05-07 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('voice_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_url', models.URLField()),
                ('speed', models.FloatField()),
                ('pitch', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tts_generation.voice')),
            ],
        ),
    ]
