# Generated by Django 5.2 on 2025-05-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts_generation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedvoice',
            name='audio_url',
        ),
        migrations.RemoveField(
            model_name='generatedvoice',
            name='pitch',
        ),
        migrations.AddField(
            model_name='generatedvoice',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='generated_audio/'),
        ),
        migrations.AddField(
            model_name='generatedvoice',
            name='pitch_shift',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='generatedvoice',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generatedvoice',
            name='speed',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='voice',
            name='language',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='voice',
            name='voice_type',
            field=models.CharField(max_length=100),
        ),
    ]
