# Generated by Django 5.2.1 on 2025-05-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts_generation', '0002_remove_generatedvoice_audio_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedvoice',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
