# Generated by Django 5.2 on 2025-05-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts_generation', '0002_remove_generatedvoice_audio_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedvoice',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedvoice',
            name='style',
            field=models.CharField(blank=True, choices=[('funny', 'Funny'), ('serious', 'Serious')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='generatedvoice',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='generated_video/'),
        ),
    ]
