# Generated by Django 5.1.7 on 2025-05-02 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_base64', models.TextField()),
                ('resolution', models.CharField(max_length=20)),
                ('frame_count', models.IntegerField()),
                ('total_duration', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
